add_unit_test(TARGET_NAME unique SOURCE_FILES unique_test.cpp)
add_unit_test(TARGET_NAME contains SOURCE_FILES contains_test.cpp)
add_unit_test(TARGET_NAME first_index_of SOURCE_FILES first_index_of_test.cpp)
add_unit_test(TARGET_NAME jage-mp-max-value SOURCE_FILES max_value_test.cpp)

add_subdirectory(concepts)