sudo apt install -y \
    build-essential \
    clangd-17 \
    cmake \
    cppcheck \
    freeglut3-dev \
    g++ \
    iwyu \
    libassimp-dev \
    libboost1.81-all-dev \
    libflac-dev \
    libfreetype-dev \
    libgl-dev \
    libglew-dev \
    libglfw3 \
    libglfw3-dev \
    libglm-dev \
    libgtest-dev \
    libopenal-dev \
    libspdlog-dev \
    libudev-dev \
    libvorbis-dev \
    libx11-dev \
    libxcursor-dev \
    llvm-17 \
    llvm-17-dev \
    ninja-build \
    vorbisgain \
    vorbis-tools
